- name: adjust sysctl file
  blockinfile: 
    dest: /etc/sysctl.conf
    content: |
      vm.swappiness = 10
      net.core.somaxconn = 4096
      net.core.wmem_max = 67108864
      net.core.rmem_max = 67108864
      net.ipv4.tcp_rmem = 4096 87380 67108864
      net.ipv4.tcp_wmem = 4096 65536 67108864
      net.ipv4.tcp_tw_reuse = 1
      net.ipv4.tcp_keepalive_time = 60
      net.core.netdev_max_backlog = 8192
      net.ipv4.tcp_max_syn_backlog = 8192
      net.ipv4.ip_local_port_range = 10240 65535
  notify: sysctl reload
  when: ansible_system == 'Linux'
