---
- name: apt-update
  command: /usr/bin/apt-get update

- name: sysctl reload
  command: sysctl -p

- name: swapon
  shell: swapon /var/swap-file

- name: restart-logstash
  service: name=logstash state=restarted

- name: reload rsyslog
  service: name=rsyslog state=restarted

- name: remount data
  command: mount /data
